### PR TITLE
Create pull-request-template.md

### LINKED ISSUE #6: [feat] Add PR Template for Consistency
## Description

A PR template will ensure that everyone follows a certain way to create, describe the changes while opening a PR.

### PR DESCRIPTION
**Pull request by shubhsharma19**
## Description 
PR template

## Issue
Closes #6

### CODE REVIEW

**Review by prakhartiwari0 — APPROVED** [review]
Good work, this was needed!

**Comment by prakhartiwari0** [comment]
@shubhsharma19 Please verify once if this contribution is reflected on your Hacktoberfest profile.

**Comment by shubhsharma19** [comment]
> @shubhsharma19 Please verify once if this contribution is reflected on your Hacktoberfest profile.

Yes its in the 7 days review period :D Thanks

**Comment by prakhartiwari0** [comment]
> > @shubhsharma19 Please verify once if this contribution is reflected on your Hacktoberfest profile.
> 
> Yes its in the 7 days review period :D Thanks

Cool then! Congrats :)

**Pull request merged**
